# -*- coding: utf-8 -*-
"""Modelos neuronalesV3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1cG03IecLKNMn7kfHrMJou_4lGYyTZUQ4

### **Improtación y libreriras**
"""

#pip install ucimlrepo

# Commented out IPython magic to ensure Python compatibility.
# %matplotlib inline
import numpy as np
import scipy as sp
import matplotlib as mpl
import matplotlib.pyplot as plt
import pandas as pd
import tensorflow as tf
import sklearn as sk
import seaborn as sns
import sys
#from ucimlrepo import fetch_ucirepo
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.tree import DecisionTreeClassifier
from sklearn.tree import plot_tree
from imblearn.over_sampling import SMOTE
from google.colab import files

uploaded = files.upload()

#utilizando la API de UCIREPO
#phishing_websites = fetch_ucirepo(id=327)
#features = phishing_websites.data.features
#resultado = phishing_websites.data.targets

#Utilizando Kaggel
dataset = pd.read_csv('/content/phishing.csv')
dataset = dataset.drop(columns=['Index'])

"""### **Lectura de los datos**"""

features = dataset.drop(columns=['class'])
resultado = dataset['class']

print("--------------------Distribucion de sitios web malicioso y oficiales---------------\n")
print("1: oficial y legitimo")
print("-1: phishing")
print(resultado.value_counts())


plt.figure(figsize=(8, 6))
sns.countplot(x=resultado, palette='magma')
plt.title('Distribución de Sitios Web: Legítimos vs Phishing', fontsize=14)
plt.xlabel('Clase (-1: Phishing, 1: Legítimo)', fontsize=12)
plt.ylabel('Número de Instancias', fontsize=12)
plt.show()


print("------------------------------valores faltantes------------------\n")
print(resultado.isnull().sum())
print(features.isnull().sum())

print("----------------------info general----------------------\n")
print(dataset.info)

print("-----------------------------Matriz de correlación-----------------\n")
plt.figure(figsize=(15, 10))
sns.heatmap(features.assign(target=resultado).corr(), annot=False, cmap='coolwarm')
plt.title('Matriz de Correlación')
plt.show()

"""### **Preprocesamiento**"""

features_Elegidas = dataset[['HTTPS','AnchorURL','PrefixSuffix-','WebsiteTraffic','SubDomains','RequestURL']]
resultados = dataset['class']

features_SMOTE, resultado_SMOTE = SMOTE(sampling_strategy='minority', random_state=42).fit_resample(features_Elegidas, resultados)
features_Balance, resultado_Balance = sk.utils.shuffle(features_SMOTE, resultado_SMOTE, random_state=42)

plt.figure(figsize=(8, 6))
sns.countplot(x=resultado_SMOTE, palette='magma')
plt.title('Distribución de Sitios Web: Legítimos vs Phishing', fontsize=14)
plt.xlabel('Clase (-1: Phishing, 1: Legítimo)', fontsize=12)
plt.ylabel('Número de Instancias', fontsize=12)
plt.show()

print(features_Balance.count())
print(resultado_Balance.count())

resultados_transform = resultado_Balance.replace(-1,0)


if(resultados_transform.value_counts()[0] == resultados_transform.value_counts()[1]):
    print("-------Dataset balanceado------")
else:
    print("----------Dataset desbalanceado--------")

features_entrenamiento, features_prueba, resultado_entrenamiento, resultado_prueba = train_test_split(features_Balance, resultados_transform, test_size=0.2, random_state=42)

features_prueba, feature_validation, resultado_prueba, resultado_validation = train_test_split(features_prueba, resultado_prueba, test_size=0.2, random_state=42)

features_entrenamiento_final = StandardScaler().fit_transform(features_entrenamiento)

features_prueba_Final = StandardScaler().fit_transform(features_prueba)

print("--------------------features entrenamiento------------------\n")
print(features_entrenamiento_final)
print("--------------------features prueba------------------\n")
print(features_prueba_Final)
print("--------------------resultados entrnamiento------------------\n")
print(resultado_entrenamiento)
print("--------------------resultados prueba------------------\n")
print(resultado_prueba)

"""# **Modelo de redes neuronales usando arbol de desiciones**

"""

model = DecisionTreeClassifier(max_depth=6, random_state=42)

model.fit(features_entrenamiento, resultado_entrenamiento,)

plt.figure(figsize=(20,10))
plot_tree(model,feature_names=features_entrenamiento.columns,class_names=["Legitimo", "Phishing"],filled=True)
plt.show()

modelopredict = model.predict(features_prueba)

predicciones = np.array(modelopredict).flatten()
reales = np.array(resultado_prueba).flatten()

TP = 0
TN = 0
FP = 0
FN = 0

for i in range(len(reales)):
    if predicciones[i] == 1:
        if reales[i] == 1:
            TP = TP + 1
        else:
            FP = FP + 1
    else:
        if reales[i] == 0:
            TN = TN + 1
        else:
            FN = FN + 1

print("--- MATRIZ DE CONFUSIÓN---")
print(f"{'                '} | 'Real Phishing (0)' | 'Real Legítimo (1)'")
print("------------------------------------------------------------------------" )
print(f"'Pred Phishing(0)' | {TN} | {FN}")
print(f"'Pred Legítimo(1)' | {FP} | {TP}")
print("------------------------------------------------------------------------" )

if (TN + FP) > 0:
    recall_phishing = TN / (TN + FP)
    precision_phishing = TN / (TN + FN)
    if (precision_phishing + recall_phishing) > 0:
        F1Score = 2 * (precision_phishing * recall_phishing) / (precision_phishing + recall_phishing)
    else:
        F1Score = 0
    print(f"Recall de Phishing: {recall_phishing:.2%}")
    print(f"Precisión de Phishing {precision_phishing:.2%}")
    print(f"F1-Score de Phishing: {F1Score:.2%}")
else:
    print("No hay casos de Phishing en el set de prueba.")