# -*- coding: utf-8 -*-
"""Modelos neuronales.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1un1OTnAzgDjEMcoGiebE9CJl4l3zVDQj

Improtación y libreriras
"""

#pip install ucimlrepo

# Commented out IPython magic to ensure Python compatibility.
# %matplotlib inline
import numpy as np
import scipy as sp
import matplotlib as mpl
import matplotlib.pyplot as plt
import pandas as pd
import tensorflow as tf
import sklearn as sk
import seaborn as sns
import sys
#from ucimlrepo import fetch_ucirepo
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from imblearn.over_sampling import SMOTE
from google.colab import files

uploaded = files.upload()

#utilizando la API de UCIREPO
#phishing_websites = fetch_ucirepo(id=327)
#features = phishing_websites.data.features
#resultado = phishing_websites.data.targets

#Utilizando Kaggel
dataset = pd.read_csv('/content/phishing.csv')
dataset = dataset.drop(columns=['Index'])

features = dataset.drop(columns=['class'])
resultado = dataset['class']

print("--------------------Distribucion de sitios web malicioso y oficiales---------------\n")
print("1: oficial y legitimo")
print("-1: phishing")
print(resultado.value_counts())


plt.figure(figsize=(8, 6))
sns.countplot(x=resultado, palette='magma')
plt.title('Distribución de Sitios Web: Legítimos vs Phishing', fontsize=14)
plt.xlabel('Clase (-1: Phishing, 1: Legítimo)', fontsize=12)
plt.ylabel('Número de Instancias', fontsize=12)
plt.show()


print("------------------------------valores faltantes------------------\n")
print(resultado.isnull().sum())
print(features.isnull().sum())

print("----------------------info general----------------------\n")
print(dataset.info)

print("-----------------------------Matriz de correlación-----------------\n")
plt.figure(figsize=(15, 10))
sns.heatmap(features.assign(target=resultado).corr(), annot=False, cmap='coolwarm')
plt.title('Matriz de Correlación')
plt.show()

"""Preprocesamiento"""

features_Elegidas = dataset[['HTTPS','AnchorURL','PrefixSuffix-','WebsiteTraffic','SubDomains','RequestURL']]
resultados = dataset['class']

features_SMOTE, resultado_SMOTE = SMOTE(sampling_strategy='minority', random_state=42).fit_resample(features_Elegidas, resultados)
features_Balance, resultado_Balance = sk.utils.shuffle(features_SMOTE, resultado_SMOTE, random_state=42)

print(features_Balance.count())
print(resultado_Balance.count())

resultados_transform = resultado_Balance.replace(-1,0)


if(resultados_transform.value_counts()[0] == resultados_transform.value_counts()[1]):
    print("-------Dataset balanceado------")
else:
    print("----------Dataset desbalanceado--------")

features_entrenamiento, features_prueba, resultado_entrenamiento, resultado_prueba = train_test_split(features_Balance, resultados_transform, test_size=0.2, random_state=42)

features_entrenamiento_final = StandardScaler().fit_transform(features_entrenamiento)

features_prueba_Final = StandardScaler().fit_transform(features_prueba)

print("--------------------features entrenamiento------------------\n")
print(features_entrenamiento_final)
print("--------------------features prueba------------------\n")
print(features_prueba_Final)
print("--------------------resultados entrnamiento------------------\n")
print(resultado_entrenamiento)
print("--------------------resultados prueba------------------\n")
print(resultado_prueba)